/*
 * This file is generated by jOOQ.
 */
package com.kamarkaka.jooq.model.tables.records;


import com.kamarkaka.jooq.model.tables.AppHeaders;

import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AppHeadersRecord extends UpdatableRecordImpl<AppHeadersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.app_headers.header_id</code>.
     */
    public void setHeaderId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.app_headers.header_id</code>.
     */
    public Integer getHeaderId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.app_headers.app_id</code>.
     */
    public void setAppId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.app_headers.app_id</code>.
     */
    public UUID getAppId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.app_headers.type</code>.
     */
    public void setType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.app_headers.type</code>.
     */
    public String getType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.app_headers.key</code>.
     */
    public void setKey(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.app_headers.key</code>.
     */
    public String getKey() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.app_headers.value</code>.
     */
    public void setValue(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.app_headers.value</code>.
     */
    public String getValue() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AppHeadersRecord
     */
    public AppHeadersRecord() {
        super(AppHeaders.APP_HEADERS);
    }

    /**
     * Create a detached, initialised AppHeadersRecord
     */
    public AppHeadersRecord(Integer headerId, UUID appId, String type, String key, String value) {
        super(AppHeaders.APP_HEADERS);

        setHeaderId(headerId);
        setAppId(appId);
        setType(type);
        setKey(key);
        setValue(value);
        resetTouchedOnNotNull();
    }
}
