/*
 * This file is generated by jOOQ.
 */
package com.kamarkaka.jooq.model.tables.records;


import com.kamarkaka.jooq.model.tables.Apps;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AppsRecord extends UpdatableRecordImpl<AppsRecord> implements Record8<UUID, String, String, String, String, String, OffsetDateTime, Boolean> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.apps.app_id</code>.
     */
    public void setAppId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.apps.app_id</code>.
     */
    public UUID getAppId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.apps.app_name</code>.
     */
    public void setAppName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.apps.app_name</code>.
     */
    public String getAppName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.apps.url_base</code>.
     */
    public void setUrlBase(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.apps.url_base</code>.
     */
    public String getUrlBase() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.apps.url_begin</code>.
     */
    public void setUrlBegin(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.apps.url_begin</code>.
     */
    public String getUrlBegin() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.apps.filename</code>.
     */
    public void setFilename(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.apps.filename</code>.
     */
    public String getFilename() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.apps.hash_md5</code>.
     */
    public void setHashMd5(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.apps.hash_md5</code>.
     */
    public String getHashMd5() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.apps.last_update</code>.
     */
    public void setLastUpdate(OffsetDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.apps.last_update</code>.
     */
    public OffsetDateTime getLastUpdate() {
        return (OffsetDateTime) get(6);
    }

    /**
     * Setter for <code>public.apps.force_download</code>.
     */
    public void setForceDownload(Boolean value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.apps.force_download</code>.
     */
    public Boolean getForceDownload() {
        return (Boolean) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<UUID, String, String, String, String, String, OffsetDateTime, Boolean> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<UUID, String, String, String, String, String, OffsetDateTime, Boolean> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Apps.APPS.APP_ID;
    }

    @Override
    public Field<String> field2() {
        return Apps.APPS.APP_NAME;
    }

    @Override
    public Field<String> field3() {
        return Apps.APPS.URL_BASE;
    }

    @Override
    public Field<String> field4() {
        return Apps.APPS.URL_BEGIN;
    }

    @Override
    public Field<String> field5() {
        return Apps.APPS.FILENAME;
    }

    @Override
    public Field<String> field6() {
        return Apps.APPS.HASH_MD5;
    }

    @Override
    public Field<OffsetDateTime> field7() {
        return Apps.APPS.LAST_UPDATE;
    }

    @Override
    public Field<Boolean> field8() {
        return Apps.APPS.FORCE_DOWNLOAD;
    }

    @Override
    public UUID component1() {
        return getAppId();
    }

    @Override
    public String component2() {
        return getAppName();
    }

    @Override
    public String component3() {
        return getUrlBase();
    }

    @Override
    public String component4() {
        return getUrlBegin();
    }

    @Override
    public String component5() {
        return getFilename();
    }

    @Override
    public String component6() {
        return getHashMd5();
    }

    @Override
    public OffsetDateTime component7() {
        return getLastUpdate();
    }

    @Override
    public Boolean component8() {
        return getForceDownload();
    }

    @Override
    public UUID value1() {
        return getAppId();
    }

    @Override
    public String value2() {
        return getAppName();
    }

    @Override
    public String value3() {
        return getUrlBase();
    }

    @Override
    public String value4() {
        return getUrlBegin();
    }

    @Override
    public String value5() {
        return getFilename();
    }

    @Override
    public String value6() {
        return getHashMd5();
    }

    @Override
    public OffsetDateTime value7() {
        return getLastUpdate();
    }

    @Override
    public Boolean value8() {
        return getForceDownload();
    }

    @Override
    public AppsRecord value1(UUID value) {
        setAppId(value);
        return this;
    }

    @Override
    public AppsRecord value2(String value) {
        setAppName(value);
        return this;
    }

    @Override
    public AppsRecord value3(String value) {
        setUrlBase(value);
        return this;
    }

    @Override
    public AppsRecord value4(String value) {
        setUrlBegin(value);
        return this;
    }

    @Override
    public AppsRecord value5(String value) {
        setFilename(value);
        return this;
    }

    @Override
    public AppsRecord value6(String value) {
        setHashMd5(value);
        return this;
    }

    @Override
    public AppsRecord value7(OffsetDateTime value) {
        setLastUpdate(value);
        return this;
    }

    @Override
    public AppsRecord value8(Boolean value) {
        setForceDownload(value);
        return this;
    }

    @Override
    public AppsRecord values(UUID value1, String value2, String value3, String value4, String value5, String value6, OffsetDateTime value7, Boolean value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AppsRecord
     */
    public AppsRecord() {
        super(Apps.APPS);
    }

    /**
     * Create a detached, initialised AppsRecord
     */
    public AppsRecord(UUID appId, String appName, String urlBase, String urlBegin, String filename, String hashMd5, OffsetDateTime lastUpdate, Boolean forceDownload) {
        super(Apps.APPS);

        setAppId(appId);
        setAppName(appName);
        setUrlBase(urlBase);
        setUrlBegin(urlBegin);
        setFilename(filename);
        setHashMd5(hashMd5);
        setLastUpdate(lastUpdate);
        setForceDownload(forceDownload);
        resetChangedOnNotNull();
    }
}
