/*
 * This file is generated by jOOQ.
 */
package com.kamarkaka.jooq.model.tables.records;


import com.kamarkaka.jooq.model.tables.Apps;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AppsRecord extends UpdatableRecordImpl<AppsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.apps.app_id</code>.
     */
    public void setAppId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.apps.app_id</code>.
     */
    public UUID getAppId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.apps.app_name</code>.
     */
    public void setAppName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.apps.app_name</code>.
     */
    public String getAppName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.apps.url_base</code>.
     */
    public void setUrlBase(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.apps.url_base</code>.
     */
    public String getUrlBase() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.apps.url_begin</code>.
     */
    public void setUrlBegin(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.apps.url_begin</code>.
     */
    public String getUrlBegin() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.apps.filename</code>.
     */
    public void setFilename(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.apps.filename</code>.
     */
    public String getFilename() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.apps.hash_md5</code>.
     */
    public void setHashMd5(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.apps.hash_md5</code>.
     */
    public String getHashMd5() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.apps.last_update</code>.
     */
    public void setLastUpdate(OffsetDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.apps.last_update</code>.
     */
    public OffsetDateTime getLastUpdate() {
        return (OffsetDateTime) get(6);
    }

    /**
     * Setter for <code>public.apps.force_download</code>.
     */
    public void setForceDownload(Boolean value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.apps.force_download</code>.
     */
    public Boolean getForceDownload() {
        return (Boolean) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AppsRecord
     */
    public AppsRecord() {
        super(Apps.APPS);
    }

    /**
     * Create a detached, initialised AppsRecord
     */
    public AppsRecord(UUID appId, String appName, String urlBase, String urlBegin, String filename, String hashMd5, OffsetDateTime lastUpdate, Boolean forceDownload) {
        super(Apps.APPS);

        setAppId(appId);
        setAppName(appName);
        setUrlBase(urlBase);
        setUrlBegin(urlBegin);
        setFilename(filename);
        setHashMd5(hashMd5);
        setLastUpdate(lastUpdate);
        setForceDownload(forceDownload);
        resetTouchedOnNotNull();
    }
}
