/*
 * This file is generated by jOOQ.
 */
package com.kamarkaka.jooq.model;


import com.kamarkaka.jooq.model.tables.AppHeaders;
import com.kamarkaka.jooq.model.tables.AppPatterns;
import com.kamarkaka.jooq.model.tables.Apps;
import com.kamarkaka.jooq.model.tables.records.AppHeadersRecord;
import com.kamarkaka.jooq.model.tables.records.AppPatternsRecord;
import com.kamarkaka.jooq.model.tables.records.AppsRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AppHeadersRecord> APP_HEADERS_PKEY = Internal.createUniqueKey(AppHeaders.APP_HEADERS, DSL.name("app_headers_pkey"), new TableField[] { AppHeaders.APP_HEADERS.HEADER_ID }, true);
    public static final UniqueKey<AppPatternsRecord> APP_PATTERNS_PKEY = Internal.createUniqueKey(AppPatterns.APP_PATTERNS, DSL.name("app_patterns_pkey"), new TableField[] { AppPatterns.APP_PATTERNS.PATTERN_ID }, true);
    public static final UniqueKey<AppsRecord> APPS_PKEY = Internal.createUniqueKey(Apps.APPS, DSL.name("apps_pkey"), new TableField[] { Apps.APPS.APP_ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<AppPatternsRecord, AppsRecord> APP_PATTERNS__FK1_APP_ID = Internal.createForeignKey(AppPatterns.APP_PATTERNS, DSL.name("FK1_app_id"), new TableField[] { AppPatterns.APP_PATTERNS.APP_ID }, Keys.APPS_PKEY, new TableField[] { Apps.APPS.APP_ID }, true);
}
