/*
 * This file is generated by jOOQ.
 */
package com.kamarkaka.jooq.model;


import com.kamarkaka.jooq.model.tables.AppHeaders;
import com.kamarkaka.jooq.model.tables.AppPatterns;
import com.kamarkaka.jooq.model.tables.Apps;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.app_headers</code>.
     */
    public final AppHeaders APP_HEADERS = AppHeaders.APP_HEADERS;

    /**
     * The table <code>public.app_patterns</code>.
     */
    public final AppPatterns APP_PATTERNS = AppPatterns.APP_PATTERNS;

    /**
     * The table <code>public.apps</code>.
     */
    public final Apps APPS = Apps.APPS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            AppHeaders.APP_HEADERS,
            AppPatterns.APP_PATTERNS,
            Apps.APPS
        );
    }
}
