/*
 * This file is generated by jOOQ.
 */
package com.kamarkaka.jooq.model;


import com.kamarkaka.jooq.model.tables.AppHeaders;
import com.kamarkaka.jooq.model.tables.AppPatterns;
import com.kamarkaka.jooq.model.tables.Apps;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.app_headers</code>.
     */
    public static final AppHeaders APP_HEADERS = AppHeaders.APP_HEADERS;

    /**
     * The table <code>public.app_patterns</code>.
     */
    public static final AppPatterns APP_PATTERNS = AppPatterns.APP_PATTERNS;

    /**
     * The table <code>public.apps</code>.
     */
    public static final Apps APPS = Apps.APPS;
}
