/*
 * This file is generated by jOOQ.
 */
package com.kamarkaka.jooq.model.tables;


import com.kamarkaka.jooq.model.Keys;
import com.kamarkaka.jooq.model.Public;
import com.kamarkaka.jooq.model.tables.records.AppHeadersRecord;

import java.util.Collection;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AppHeaders extends TableImpl<AppHeadersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.app_headers</code>
     */
    public static final AppHeaders APP_HEADERS = new AppHeaders();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AppHeadersRecord> getRecordType() {
        return AppHeadersRecord.class;
    }

    /**
     * The column <code>public.app_headers.header_id</code>.
     */
    public final TableField<AppHeadersRecord, Integer> HEADER_ID = createField(DSL.name("header_id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.app_headers.app_id</code>.
     */
    public final TableField<AppHeadersRecord, UUID> APP_ID = createField(DSL.name("app_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.app_headers.type</code>.
     */
    public final TableField<AppHeadersRecord, String> TYPE = createField(DSL.name("type"), SQLDataType.VARCHAR(8).nullable(false), this, "");

    /**
     * The column <code>public.app_headers.key</code>.
     */
    public final TableField<AppHeadersRecord, String> KEY = createField(DSL.name("key"), SQLDataType.VARCHAR(16).nullable(false), this, "");

    /**
     * The column <code>public.app_headers.value</code>.
     */
    public final TableField<AppHeadersRecord, String> VALUE = createField(DSL.name("value"), SQLDataType.CLOB.nullable(false), this, "");

    private AppHeaders(Name alias, Table<AppHeadersRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AppHeaders(Name alias, Table<AppHeadersRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.app_headers</code> table reference
     */
    public AppHeaders(String alias) {
        this(DSL.name(alias), APP_HEADERS);
    }

    /**
     * Create an aliased <code>public.app_headers</code> table reference
     */
    public AppHeaders(Name alias) {
        this(alias, APP_HEADERS);
    }

    /**
     * Create a <code>public.app_headers</code> table reference
     */
    public AppHeaders() {
        this(DSL.name("app_headers"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<AppHeadersRecord, Integer> getIdentity() {
        return (Identity<AppHeadersRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<AppHeadersRecord> getPrimaryKey() {
        return Keys.APP_HEADERS_PKEY;
    }

    @Override
    public AppHeaders as(String alias) {
        return new AppHeaders(DSL.name(alias), this);
    }

    @Override
    public AppHeaders as(Name alias) {
        return new AppHeaders(alias, this);
    }

    @Override
    public AppHeaders as(Table<?> alias) {
        return new AppHeaders(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AppHeaders rename(String name) {
        return new AppHeaders(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AppHeaders rename(Name name) {
        return new AppHeaders(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AppHeaders rename(Table<?> name) {
        return new AppHeaders(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppHeaders where(Condition condition) {
        return new AppHeaders(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppHeaders where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppHeaders where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppHeaders where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AppHeaders where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AppHeaders where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AppHeaders where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AppHeaders where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppHeaders whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppHeaders whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
