/*
 * This file is generated by jOOQ.
 */
package com.kamarkaka.jooq.model.tables;


import com.kamarkaka.jooq.model.Keys;
import com.kamarkaka.jooq.model.Public;
import com.kamarkaka.jooq.model.tables.Apps.AppsPath;
import com.kamarkaka.jooq.model.tables.records.AppPatternsRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AppPatterns extends TableImpl<AppPatternsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.app_patterns</code>
     */
    public static final AppPatterns APP_PATTERNS = new AppPatterns();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AppPatternsRecord> getRecordType() {
        return AppPatternsRecord.class;
    }

    /**
     * The column <code>public.app_patterns.pattern_id</code>.
     */
    public final TableField<AppPatternsRecord, Integer> PATTERN_ID = createField(DSL.name("pattern_id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.app_patterns.app_id</code>.
     */
    public final TableField<AppPatternsRecord, UUID> APP_ID = createField(DSL.name("app_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.app_patterns.pattern</code>.
     */
    public final TableField<AppPatternsRecord, String> PATTERN = createField(DSL.name("pattern"), SQLDataType.CLOB.nullable(false), this, "");

    private AppPatterns(Name alias, Table<AppPatternsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AppPatterns(Name alias, Table<AppPatternsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.app_patterns</code> table reference
     */
    public AppPatterns(String alias) {
        this(DSL.name(alias), APP_PATTERNS);
    }

    /**
     * Create an aliased <code>public.app_patterns</code> table reference
     */
    public AppPatterns(Name alias) {
        this(alias, APP_PATTERNS);
    }

    /**
     * Create a <code>public.app_patterns</code> table reference
     */
    public AppPatterns() {
        this(DSL.name("app_patterns"), null);
    }

    public <O extends Record> AppPatterns(Table<O> path, ForeignKey<O, AppPatternsRecord> childPath, InverseForeignKey<O, AppPatternsRecord> parentPath) {
        super(path, childPath, parentPath, APP_PATTERNS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class AppPatternsPath extends AppPatterns implements Path<AppPatternsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> AppPatternsPath(Table<O> path, ForeignKey<O, AppPatternsRecord> childPath, InverseForeignKey<O, AppPatternsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private AppPatternsPath(Name alias, Table<AppPatternsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public AppPatternsPath as(String alias) {
            return new AppPatternsPath(DSL.name(alias), this);
        }

        @Override
        public AppPatternsPath as(Name alias) {
            return new AppPatternsPath(alias, this);
        }

        @Override
        public AppPatternsPath as(Table<?> alias) {
            return new AppPatternsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<AppPatternsRecord, Integer> getIdentity() {
        return (Identity<AppPatternsRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<AppPatternsRecord> getPrimaryKey() {
        return Keys.APP_PATTERNS_PKEY;
    }

    @Override
    public List<ForeignKey<AppPatternsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.APP_PATTERNS__FK1_APP_ID);
    }

    private transient AppsPath _apps;

    /**
     * Get the implicit join path to the <code>public.apps</code> table.
     */
    public AppsPath apps() {
        if (_apps == null)
            _apps = new AppsPath(this, Keys.APP_PATTERNS__FK1_APP_ID, null);

        return _apps;
    }

    @Override
    public AppPatterns as(String alias) {
        return new AppPatterns(DSL.name(alias), this);
    }

    @Override
    public AppPatterns as(Name alias) {
        return new AppPatterns(alias, this);
    }

    @Override
    public AppPatterns as(Table<?> alias) {
        return new AppPatterns(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AppPatterns rename(String name) {
        return new AppPatterns(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AppPatterns rename(Name name) {
        return new AppPatterns(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AppPatterns rename(Table<?> name) {
        return new AppPatterns(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppPatterns where(Condition condition) {
        return new AppPatterns(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppPatterns where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppPatterns where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppPatterns where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AppPatterns where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AppPatterns where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AppPatterns where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AppPatterns where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppPatterns whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppPatterns whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
