/*
 * This file is generated by jOOQ.
 */
package com.kamarkaka.jooq.model.tables;


import com.kamarkaka.jooq.model.Keys;
import com.kamarkaka.jooq.model.Public;
import com.kamarkaka.jooq.model.tables.AppPatterns.AppPatternsPath;
import com.kamarkaka.jooq.model.tables.records.AppsRecord;

import java.time.OffsetDateTime;
import java.util.Collection;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Apps extends TableImpl<AppsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.apps</code>
     */
    public static final Apps APPS = new Apps();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AppsRecord> getRecordType() {
        return AppsRecord.class;
    }

    /**
     * The column <code>public.apps.app_id</code>.
     */
    public final TableField<AppsRecord, UUID> APP_ID = createField(DSL.name("app_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.apps.app_name</code>.
     */
    public final TableField<AppsRecord, String> APP_NAME = createField(DSL.name("app_name"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.apps.url_base</code>.
     */
    public final TableField<AppsRecord, String> URL_BASE = createField(DSL.name("url_base"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.apps.url_begin</code>.
     */
    public final TableField<AppsRecord, String> URL_BEGIN = createField(DSL.name("url_begin"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.apps.filename</code>.
     */
    public final TableField<AppsRecord, String> FILENAME = createField(DSL.name("filename"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.apps.hash_md5</code>.
     */
    public final TableField<AppsRecord, String> HASH_MD5 = createField(DSL.name("hash_md5"), SQLDataType.CHAR(32), this, "");

    /**
     * The column <code>public.apps.last_update</code>.
     */
    public final TableField<AppsRecord, OffsetDateTime> LAST_UPDATE = createField(DSL.name("last_update"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.apps.force_download</code>.
     */
    public final TableField<AppsRecord, Boolean> FORCE_DOWNLOAD = createField(DSL.name("force_download"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    private Apps(Name alias, Table<AppsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Apps(Name alias, Table<AppsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.apps</code> table reference
     */
    public Apps(String alias) {
        this(DSL.name(alias), APPS);
    }

    /**
     * Create an aliased <code>public.apps</code> table reference
     */
    public Apps(Name alias) {
        this(alias, APPS);
    }

    /**
     * Create a <code>public.apps</code> table reference
     */
    public Apps() {
        this(DSL.name("apps"), null);
    }

    public <O extends Record> Apps(Table<O> path, ForeignKey<O, AppsRecord> childPath, InverseForeignKey<O, AppsRecord> parentPath) {
        super(path, childPath, parentPath, APPS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class AppsPath extends Apps implements Path<AppsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> AppsPath(Table<O> path, ForeignKey<O, AppsRecord> childPath, InverseForeignKey<O, AppsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private AppsPath(Name alias, Table<AppsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public AppsPath as(String alias) {
            return new AppsPath(DSL.name(alias), this);
        }

        @Override
        public AppsPath as(Name alias) {
            return new AppsPath(alias, this);
        }

        @Override
        public AppsPath as(Table<?> alias) {
            return new AppsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<AppsRecord> getPrimaryKey() {
        return Keys.APPS_PKEY;
    }

    private transient AppPatternsPath _appPatterns;

    /**
     * Get the implicit to-many join path to the
     * <code>public.app_patterns</code> table
     */
    public AppPatternsPath appPatterns() {
        if (_appPatterns == null)
            _appPatterns = new AppPatternsPath(this, null, Keys.APP_PATTERNS__FK1_APP_ID.getInverseKey());

        return _appPatterns;
    }

    @Override
    public Apps as(String alias) {
        return new Apps(DSL.name(alias), this);
    }

    @Override
    public Apps as(Name alias) {
        return new Apps(alias, this);
    }

    @Override
    public Apps as(Table<?> alias) {
        return new Apps(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Apps rename(String name) {
        return new Apps(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Apps rename(Name name) {
        return new Apps(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Apps rename(Table<?> name) {
        return new Apps(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Apps where(Condition condition) {
        return new Apps(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Apps where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Apps where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Apps where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Apps where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Apps where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Apps where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Apps where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Apps whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Apps whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
