name: Docker CI/CD
on:
  push:
    branches: [ "main" ]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # step 1: checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # step2: login to docker hub
      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # step3: set up docker buildx
      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3

      # step4: build and push docker image
      - name: Build and push docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags:
            ${{ secrets.DOCKER_USERNAME }}/app-updater:latest
            ${{ secrets.DOCKER_USERNAME }}/app-updater:${{ github.sha }}
